 project_id = "tqmanipbztpursndogxv"
 
 [functions.scan-product]
 verify_jwt = false

 [functions.website-bot]
 verify_jwt = false

 [functions.create-payment-order]
 verify_jwt = true

 [functions.razorpay-webhook]
 verify_jwt = false